# Creating complex column vectors

# Theory of Complex Vector Spaces
Complex vector spaces extend the idea of real vector spaces by allowing vectors to have complex numbers as their components. In these spaces, vectors can be added together and multiplied by complex scalars to produce new vectors. Key operations in complex vector spaces include vector addition, scalar multiplication, vector negation, and complex conjugation.

In [22]:
import numpy as np

# Define a 2x2 square matrix
matrix = np.array([[2, 3],
                   [1, 4]])

# Define a vector of size 2
vector = np.array([5, 6])

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

# Display the result
print("Matrix:\n", matrix)
print("\nVector:\n", vector)
print("\nResult of multiplication:\n", result)



Matrix:
 [[2 3]
 [1 4]]

Vector:
 [5 6]

Result of multiplication:
 [28 29]


## Manipulating Complex Column Vectors using NumPy
Here we demonstrate how to manipulate complex column vectors using NumPy, including operations like sum, negation, multiplication by a scalar, transpose, adjunct, and conjugate.

In [23]:

import numpy as np

# Define two complex column vectors
v1 = np.array([[2+3j], [5-4j], [1+1j]])
v2 = np.array([[1-1j], [3+2j], [4-4j]])

# Sum
sum_v = v1 + v2

# Negation
neg_v1 = -v1

# Multiplication by a scalar
scalar = 2 + 1j
mult_v1 = v1 * scalar

# Transpose
transpose_v1 = v1.T

# Adjunct (Conjugate transpose)
adjunct_v1 = v1.T.conj()

# Conjugate
conjugate_v1 = np.conjugate(v1)

(sum_v, neg_v1, mult_v1, transpose_v1, adjunct_v1, conjugate_v1)


(array([[3.+2.j],
        [8.-2.j],
        [5.-3.j]]),
 array([[-2.-3.j],
        [-5.+4.j],
        [-1.-1.j]]),
 array([[ 1.+8.j],
        [14.-3.j],
        [ 1.+3.j]]),
 array([[2.+3.j, 5.-4.j, 1.+1.j]]),
 array([[2.-3.j, 5.+4.j, 1.-1.j]]),
 array([[2.-3.j],
        [5.+4.j],
        [1.-1.j]]))

# Theory of Vector Spaces using Matrices
In the context of matrices, vector spaces can be defined where each vector is a matrix of a particular size. Operations on these matrix-vector spaces include matrix addition, scalar multiplication, matrix negation, transpose, adjunct, and conjugate. In this section, we focus on square matrices of size 3x3.

## Manipulating Square Matrices using NumPy
Examples of how to manipulate 3x3 square matrices using NumPy, showing operations such as sum, negation, multiplication by a scalar, conjugate, transpose, and adjunct.

In [24]:

# Define two 3x3 complex matrices
m1 = np.array([[2+3j, 4-1j, 0], 
               [1+1j, 3+3j, 5], 
               [4, 6-2j, 1-1j]])
m2 = np.array([[1, 2+1j, 3-3j], 
               [0, -1+2j, 1-2j], 
               [3+3j, 2, 4+4j]])

# Sum
sum_m = m1 + m2

# Negation
neg_m1 = -m1

# Multiplication by a scalar
scalar = 0.5 + 0.5j
mult_m1 = m1 * scalar

# Conjugate
conjugate_m1 = np.conjugate(m1)

# Transpose
transpose_m1 = m1.T

# Adjunct (Conjugate transpose)
adjunct_m1 = m1.T.conj()

(sum_m, neg_m1, mult_m1, conjugate_m1, transpose_m1, adjunct_m1)


(array([[3.+3.j, 6.+0.j, 3.-3.j],
        [1.+1.j, 2.+5.j, 6.-2.j],
        [7.+3.j, 8.-2.j, 5.+3.j]]),
 array([[-2.-3.j, -4.+1.j, -0.-0.j],
        [-1.-1.j, -3.-3.j, -5.-0.j],
        [-4.-0.j, -6.+2.j, -1.+1.j]]),
 array([[-0.5+2.5j,  2.5+1.5j,  0. +0.j ],
        [ 0. +1.j ,  0. +3.j ,  2.5+2.5j],
        [ 2. +2.j ,  4. +2.j ,  1. +0.j ]]),
 array([[2.-3.j, 4.+1.j, 0.-0.j],
        [1.-1.j, 3.-3.j, 5.-0.j],
        [4.-0.j, 6.+2.j, 1.+1.j]]),
 array([[2.+3.j, 1.+1.j, 4.+0.j],
        [4.-1.j, 3.+3.j, 6.-2.j],
        [0.+0.j, 5.+0.j, 1.-1.j]]),
 array([[2.-3.j, 1.-1.j, 4.-0.j],
        [4.+1.j, 3.-3.j, 6.+2.j],
        [0.-0.j, 5.-0.j, 1.+1.j]]))

## Checking the Dimension of a Matrix
We can check the dimension of a matrix using the `.shape` attribute.

In [25]:
# Checking the dimension of matrix1
m1 = np.array([[2+3j, 4-1j, 0], 
               [1+1j, 3+3j, 5], 
               [4, 6-2j, 1-1j]])
m1.shape

(3, 3)

## Action of a Matrix on a Vector
Finally, examples of how to use Python to multiply a 3x3 square matrix by a 3x1 column vector.

In [26]:
# Multiplying a 3x3 matrix by a 3x1 vector
result = np.dot(m1, v1)
result


array([[11. -9.j],
       [31.+13.j],
       [32.-22.j]])

# Exercises on Complex Vectors and Matrices with Concrete Cases

This set of exercises focuses on operations with **complex column vectors** and **complex square matrices**, presenting specific cases with vectors and matrices written in LaTeX format.

## Complex Column Vector Operations

### Exercise 1: Sum of Two Complex Vectors
Given two complex vectors:

$$ v1 = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $$

and

$$ v2 = \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} $$

find their sum.

### Solution:
The result of the addition, as shown by the code execution, is:

$$ v3 = \begin{bmatrix} 3 + i \\ 7 + i \end{bmatrix} $$


In [27]:
import numpy as np

# Define two complex column vectors
v1 = np.array([[1 + 2j], [3 - 1j]])
v2 = np.array([[2 - 1j], [4 + 2j]])

# Compute the sum of the two vectors
sum_m = v1 + v2

# Display the results
print("v1 =", v1, "\nv2 =", v2, "\nsum =", sum_m)


v1 = [[1.+2.j]
 [3.-1.j]] 
v2 = [[2.-1.j]
 [4.+2.j]] 
sum = [[3.+1.j]
 [7.+1.j]]


### Exercise 2: Negation of a Complex Vector
Given a complex vector:

$$ v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $$

find its negation.

### Solution:
The negation, as shown by the code execution, is:

$$ -v = \begin{bmatrix} -2 - 3i \\ -1 + 2i \end{bmatrix} $$


In [28]:
import numpy as np

# Define a complex column vector
v1 = np.array([[2 + 3j], [1 - 2j]])

# Compute the negation of the vector
negation = -v1

# Display the results
print("v1 =", v1, "\n-v1 =", negation)


v1 = [[2.+3.j]
 [1.-2.j]] 
-v1 = [[-2.-3.j]
 [-1.+2.j]]


### Exercise 3: Multiplication of a Complex Vector by a Scalar
Multiply the complex vector:

$$ v = \begin{bmatrix} 1 - i \\ 2 + 2i \end{bmatrix} $$

by the complex scalar:

$$ 3 + i $$

### Solution:
As shown by the code execution, the multiplication is:

$$ v = \begin{bmatrix} 4 - 2i \\ 4 + 8i \end{bmatrix} $$


In [29]:
import numpy as np

# Define a complex column vector
v1 = np.array([[1 - 1j], [2 + 2j]])

# Define the complex scalar
scalar = 3 + 1j

# Multiply the vector by the scalar
mult = scalar * v1

# Display the results
print("v1 =", v1, "\nscalar =", scalar, "\nv1 * scalar =", mult)


v1 = [[1.-1.j]
 [2.+2.j]] 
scalar = (3+1j) 
v1 * scalar = [[4.-2.j]
 [4.+8.j]]


### Exercise 4: Transpose of a Complex Vector
Find the transpose of the complex vector:

$$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix} $$

### Solution:
The result of taking the transpose of the vector is:

$$ v^T = \begin{bmatrix} 2 - i & 3 + 4i \end{bmatrix} $$


In [30]:
import numpy as np

# Define a complex column vector
v1 = np.array([[2 - 1j], [3 + 4j]])

# Compute the transpose of the vector
transpose_v1 = v1.T

# Display the results
print("v1 =", v1, "\nTranspose =", transpose_v1)


v1 = [[2.-1.j]
 [3.+4.j]] 
Transpose = [[2.-1.j 3.+4.j]]


### Exercise 5: Conjugate of a Complex Vector
Compute the conjugate of the complex vector:

$$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $$

### Solution:
As shown by the code execution, the result is:

$$ \overline{v} = \begin{bmatrix} 1 - i \\ 2 + 3i \end{bmatrix} $$


In [31]:
import numpy as np

# Define a complex column vector
v1 = np.array([[1 + 1j], [2 - 3j]])

# Compute the conjugate of the vector
conjugate_v1 = np.conjugate(v1)

# Display the results
print("v1 =", v1, "\nConjugate =", conjugate_v1)


v1 = [[1.+1.j]
 [2.-3.j]] 
Conjugate = [[1.-1.j]
 [2.+3.j]]


### Exercise 6: Adjoint (Conjugate Transpose) of a Complex Vector
Find the adjoint (also called the conjugate transpose) of the complex vector:

$$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $$

### Solution:
First, compute the conjugate of the vector:

$$ \overline{v} = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $$

Then, take its transpose. As shown by the code execution, the result is:

$$ \overline{v}^T = \begin{bmatrix} 1 + 2i & 3 - i \end{bmatrix} $$


In [32]:
import numpy as np

# Define a complex column vector
v1 = np.array([[1 - 2j], [3 + 1j]])

# Step 1: Compute the conjugate of the vector
conjugate_v1 = np.conjugate(v1)
print("v1 =", v1, "\nConjugate =", conjugate_v1)

# Step 2: Compute the transpose of the conjugate (adjoint)
transpose_c = conjugate_v1.T
print("Conjugate Transpose =", transpose_c)


v1 = [[1.-2.j]
 [3.+1.j]] 
Conjugate = [[1.+2.j]
 [3.-1.j]]
Conjugate Transpose = [[1.+2.j 3.-1.j]]


### Exercise 7: Sum of Two Complex Matrices
Given two complex matrices:

$$ m1 = \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix} $$

and

$$ m2 = \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} $$

calculate their sum.

### Solution:
As shown by the code execution, the result is:

$$ m3 = \begin{bmatrix} 3 - 2i & 3 - i \\ 3 + 3i & 6 + 2i \end{bmatrix} $$

In [33]:
import numpy as np

# Define two complex matrices
m1 = np.array([[1 + 1j, 2 - 1j], 
               [3 + 2j, 4 + 0j]])

m2 = np.array([[2 - 3j, 1 - 0j], 
               [0 + 1j, 2 + 2j]])

# Compute the sum of the two matrices
m3 = m1 + m2

# Display the results
print("m1 =", m1, "\nm2 =", m2, "\nm1 + m2 = m3 =", m3)


m1 = [[1.+1.j 2.-1.j]
 [3.+2.j 4.+0.j]] 
m2 = [[2.-3.j 1.+0.j]
 [0.+1.j 2.+2.j]] 
m1 + m2 = m3 = [[3.-2.j 3.-1.j]
 [3.+3.j 6.+2.j]]


### Exercise 8: Negation of a Complex Matrix
Find the negation of the complex matrix:

$$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $$

### Solution:
As shown by the code execution, the negation is:

$$ -m = \begin{bmatrix} -2 - i & -3 \\ -1 + i & -2 - 2i \end{bmatrix} $$


In [34]:
import numpy as np

# Define a complex matrix
m = np.array([[2 + 1j, 3 - 0j], 
              [1 - 1j, 2 + 2j]])

# Compute the negation of the matrix
negation = -m

# Display the results
print("m =", m, "\nNegation =", negation)


m = [[2.+1.j 3.+0.j]
 [1.-1.j 2.+2.j]] 
Negation = [[-2.-1.j -3.-0.j]
 [-1.+1.j -2.-2.j]]


### Exercise 9: Multiplication of a Complex Matrix by a Scalar
Multiply the complex matrix:

$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $$

by the complex scalar:

$$ 2 + 3i $$

### Solution:
As shown by the code execution, the multiplication is:

$$ mult = \begin{bmatrix} 5 + i & 4 + 6i \\ 3 + 11i & 14 + 8i \end{bmatrix} $$

In [35]:
import numpy as np

# Define a complex matrix
m = np.array([[1 - 1j, 2 - 0j], 
              [3 + 1j, 4 - 2j]])

# Define the complex scalar
scalar = 2 + 3j

# Multiply the matrix by the scalar
mult = m * scalar

# Display the results
print("m =", m, "\nscalar =", scalar, "\nmult =", mult)


m = [[1.-1.j 2.+0.j]
 [3.+1.j 4.-2.j]] 
scalar = (2+3j) 
mult = [[ 5. +1.j  4. +6.j]
 [ 3.+11.j 14. +8.j]]


### Exercise 10: Conjugate of a Complex Matrix
Compute the conjugate of the complex matrix:

$$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $$

### Solution:
As shown by the code output, the correct result is:

$$ \overline{m} = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $$

In [36]:
import numpy as np

# Define a complex matrix
m = np.array([[1 + 1j, 2 - 0j], 
              [3 - 1j, 4 + 2j]])

# Compute the conjugate of the matrix
conjugate_m = np.conjugate(m)

# Display the results
print("m =", m, "\nConjugate =", conjugate_m)


m = [[1.+1.j 2.+0.j]
 [3.-1.j 4.+2.j]] 
Conjugate = [[1.-1.j 2.-0.j]
 [3.+1.j 4.-2.j]]


### Exercise 11: Transpose of a Complex Matrix
Find the transpose of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $$

### Solution
As shown in the code output, the transpose of the matrix is:
$$ m^T = \begin{bmatrix} 1 - i & 3 \\ 2 + 2i & 4 - i \end{bmatrix} $$

In [37]:
import numpy as np

m = np.array([[1-1j, 2+2j],
              [3+0j, 4-1j]])

transpo = m.T
print("m =", m, "\nTranspose =", transpo)

m = [[1.-1.j 2.+2.j]
 [3.+0.j 4.-1.j]] 
Transpose = [[1.-1.j 3.+0.j]
 [2.+2.j 4.-1.j]]


### Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix
Calculate the adjunct (or conjugate transpose) of the complex matrix 
$$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $$

### Solution
First, compute the conjugate of the matrix:
$$ c = \begin{bmatrix} 1 - 2i & 3 + i \\ 4 & 5 - i \end{bmatrix} $$

Then, calculate the transpose of the conjugate, which gives:
$$ c^T = \begin{bmatrix} 1 - 2i & 4 \\ 3 + i & 5 - i \end{bmatrix} $$


In [38]:
import numpy as np

# Original complex matrix
m = np.array([[1+2j, 3-1j], 
              [4+0j, 5+1j]])

# Compute conjugate
conjugate_m = np.conjugate(m)
print("Original matrix m:\n", m)
print("Conjugate of m:\n", conjugate_m)

# Compute conjugate transpose (adjunct)
conjugate_transpose = conjugate_m.T
print("Conjugate transpose of m:\n", conjugate_transpose)


Original matrix m:
 [[1.+2.j 3.-1.j]
 [4.+0.j 5.+1.j]]
Conjugate of m:
 [[1.-2.j 3.+1.j]
 [4.-0.j 5.-1.j]]
Conjugate transpose of m:
 [[1.-2.j 4.-0.j]
 [3.+1.j 5.-1.j]]


### Exercise 13: Checking the Dimensions of a Matrix
Determine the dimensions of the complex matrix.

$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $$

### Solution:
As shown in the code output, the dimensions are:

$$ 3 \times 3 $$


In [39]:
import numpy as np

# Define the complex matrix
m = np.array([[1-1j, 2+0j], 
              [3+2j, 4-1j]])

# Print the matrix and its dimensions
print("Matrix m =\n", m)   
print("Dimensions of m =", m.shape) 


Matrix m =
 [[1.-1.j 2.+0.j]
 [3.+2.j 4.-1.j]]
Dimensions of m = (2, 2)


### Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector
Multiply the complex square matrix 
$$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $$
by the complex column vector 
$$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $$

### Solution:
As shown in the code output, the result of the multiplication is:
$$ mult = \begin{bmatrix} 8 + 6i \\ 7 + 10i \end{bmatrix} $$


In [40]:
import numpy as np

# Define the complex square matrix
m = np.array([[1+1j, 2-1j], 
              [3+0j, 4+1j]])

# Define the complex column vector
v = np.array([[2-1j], 
              [1+3j]])

# Multiply the matrix by the vector
result = np.dot(m, v)

# Print the matrix, vector, and the result
print("m =", m, "\nv =", v, "\nmultiplication =", result)


m = [[1.+1.j 2.-1.j]
 [3.+0.j 4.+1.j]] 
v = [[2.-1.j]
 [1.+3.j]] 
multiplication = [[8. +6.j]
 [7.+10.j]]
